import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminRouter from "./admin";
import webhookRouter from "./webhook";
import adsRouter from "./ads";
import contactRouter from "./contact";
import columnistsPublicRouter from "./columnists";
import msgsRouter from "./msgs";
import articlesRouter from "./articles";
import siteRouter from "./site";
import quotesRouter from "./quotes";
import sitemapRouter from "./sitemap";
import analyticsRouter from "./analytics";
import rssRouter from "./rss";
import socialRouter from "./social";
import perplexityRouter from "./perplexity";
import usersRouter from "./users";
import logsRouter from "./logs";
import permissionsRouter from "./permissions";
import webhookKeyRouter from "./webhook-key";
import uploadsRouter from "./uploads";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/uploads", uploadsRouter);
router.use("/admin", adminRouter);
router.use("/publish", webhookRouter);
router.use("/ads", adsRouter);
router.use("/columnists", columnistsPublicRouter);
router.use("/messages", msgsRouter);
router.use("/articles", articlesRouter);
router.use("/quotes", quotesRouter);
router.use(siteRouter);
router.use(sitemapRouter);
router.use("/analytics", analyticsRouter);
router.use("/admin/rss", rssRouter);
router.use("/admin/social", socialRouter);
router.use("/admin/perplexity", perplexityRouter);
router.use("/admin/users", usersRouter);
router.use("/admin/logs", logsRouter);
router.use("/admin/permissions", permissionsRouter);
router.use("/admin/webhook-key", webhookKeyRouter);

export default router;
